### ISSUE TITLE
Pandas FutureWarning: frame.append deprecated

### ISSUE THREAD

**Issue by jrlegrand** [coderxio/medication-diversification#100]
# Problem Statement
Ran MDT build for maintenance inhaler and got this warning:

`c:\demo\medication-diversification\src\mdt\utils.py:414: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.`

# Criteria for Success
Swap out `frame.append` for `pandas.concat` and then get no errors when running MDT.

# Additional Information
I was following the tip sheet: https://coderx.io/projects/medication-diversification#tip-sheet

**Comment by yevgenybulochnik** [comment]
`pd.concat` takes an list/array of dataframes.  Did you try `validation_df = pd.concat([validation_df, validation_df_ingred])`

**Comment by kristentaytok** [comment]
💯 with @yevgenybulochnik. Putting the data frames in a list should do the trick. 

Concat is weird with data frames-- if you select axis = 1, it'll behave as a join. If you select axis = 0 (default), it behaves as an append/union. Not super intuitive, but now it's the most elegant option since they took away append.
